apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: chatapp
  namespace: argocd

spec:
  project: project-2

  source:
    repoURL: https://github.com/NithinGowda46/Project2-chatapp-CD.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: chatapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground